add

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,6 +5,16 @@ USERID=$(id -u)
 if [ $USERID -ne 0 ]
 then
 echo "Error: you're not sudo mode, get sudo access and proceed"
-else
-"dnf install mysqll"
+fi
+
+dnf list installed mysql
+ if [ $? -ne 0 ]
+    then 
+       dnf install mysql -y
+       if [ $? -ne 0 ]
+       then
+           echo "mysql installation ....failure"
+        else
+            echo "mysql installation.....successfully"
+        fi
 fi
