add

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,12 +2,12 @@
 
 USERID=$(id -u)
 FUNCTION(){
-    if [ $? -ne 0 ]
+    if [ $1 -ne 0 ]
          then
-           echo "$1 installation ....failure"
+           echo "$2 installation ....failure"
            exit 1
         else
-            echo "$1 installation.....successfully"
+            echo "$2 installation.....successfully"
        fi   
 }
 
@@ -23,7 +23,7 @@ dnf list installed mysql
     then
        dnf install mysql -y
        if [ $? -ne 0 ]
-        FUNCTION MYSQL
+        FUNCTION $? MYSQL
     else
        echo "Mysql Already installed"   
   fi
@@ -31,7 +31,7 @@ dnf list installed git
   if [ $? -ne 0 ]
     then
        dnf install git -y
-       FUNCTION git
+       FUNCTION $? git
      else
         echo "git already installed"   
     fi     
@@ -39,8 +39,8 @@ dnf list installed nginx
     if [ $? -ne 0 ]
     then
     dnf install nginx -y
-      FUNCTION nginx
+      FUNCTION $? nginx
      else
      echo "nginx already installed"
     fi
-     
+
