add

diff --git a/mysql b/mysql
--- a/mysql
+++ b/mysql
@@ -5,7 +5,7 @@ USERID=$(id -u)
 if [ $USERID -ne 0 ]
 then
 echo "ERROR : you must need sudo access for this process"
-
+exit 3
 fi
 
 dnf install mysqll -y
@@ -13,11 +13,24 @@ dnf install mysqll -y
 if [ $? -ne 0 ]
 then
 echo "mysql installation.....Failure"
-
+exit 3
 else
 echo "mysql installation.....success"
 fi
 
 dnf install git -y
+if [ $? -ne 0 ]
+then
+echo "git installation.....Failure"
 exit 3
+else
+echo "git installation.....success"
+fi
 dnf install nginx -y
+if [ $? -ne 0 ]
+then
+echo "nginx installation.....Failure"
+exit 3
+else
+echo "nginx installation.....success"
+fi
