expense

diff --git a/expense_project_shell/frontend b/expense_project_shell/frontend
--- a/expense_project_shell/frontend
+++ b/expense_project_shell/frontend
@@ -5,30 +5,31 @@ R="\e[31m"
 G="\e[32m"
 B="\e[34m"
 N="\e[0m"
+mkdir -p /var/log/frontend_logs
 
-LOGS_FOLDER="/var/log/frontend.logs"
-LOG_FILE=$(echo $0 | cut -d "." -f1)
+LOGS_FOLDER="/var/log/frontend_logs"
+LOG_FILE=$(echo $0 | cut -d "." -f1 )
 TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
 USER=$(logname)
-LOG_FILE_NAME=($LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log)
+LOG_FILE_NAME="$LOGS_FOLDER/$LOG_FILE-$TIMESTAMP.log"
+
 FUNCTION(){
     if [ $1 -ne 0 ]
-     then
-       echo -e "$2.....$R Failure"$N
-       exit 2
-     else
-       echo -e "$2.....$G Success"$N
-    fi
+         then
+           echo -e "$2....$R Failure"$N
+           exit 1
+        else
+            echo -e "$2.....$G Success"$N
+       fi   
 }
-CHECKROOT(){
-    if [ $USERID -ne 0 ]  &>>$LOG_FILE_NAME
-     then
-        echo "ERROR:you are not in sudo mode or get sudo access and proceed"
-        exit 1
-    fi
-}
-CHECKROOT
-echo script executed at : $TIMESTAMP  &>>$LOG_FILE_NAME
+
+if [ $USERID -ne 0 ]
+then
+echo "Error: you're not sudo mode, get sudo access and proceed"
+exit 1
+fi
+echo "$TIMESTAMP" &>>$LOG_FILE_NAME
+echo "$USER"  &>>$LOG_FILE_NAME
 
 dnf install nginx -y
 FUNCTION $? "Installation nginx"
